sudo: false

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gem

install: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "echo 'gem: --no-rdoc --no-ri' > $HOME/.gemrc"
  - gem update --system
  - gem update bundler
  #- kerl update releases
  #- kerl build 20.3 20.3
  #- kerl install 20.3 $HOME/erlang/20.3
  #- . $HOME/erlang/20.3/activate

script:
  - ./mvnw -B -U clean verify -P help -Dmaven.test.failure.ignore=true 
  - pwd
  - ls -al .
# publish update site

after_failure:
  - cat /home/travis/build/vladdu/erlide_eclipse/tests/org.erlide.backend.tests/target/work/data/.metadata/.log

