dist: xenial

language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gem

install: true

before_script:
  - sudo apt-get install -y ant
  - export DISPLAY=:99.0
  - "echo 'gem: --no-rdoc --no-ri' > $HOME/.gemrc"
  - gem update --system
  - gem update bundler
  #- kerl update releases
  #- kerl build 20.3 20.3
  #- kerl install 20.3 $HOME/erlang/20.3
  #- . $HOME/erlang/20.3/activate

script:
  - xvfb-run ./mvnw -B -U clean verify -P help -Dmaven.test.failure.ignore=true
# publish update site

after_failure:
  - pwd
  - ls -al .
  - find $HOME/build/vladdu/erlide_eclipse/ -name ".log"

